version: '3.1'

services:
  jds-rabbit:
    image: rabbitmq:3.7-management
    ports:
      - 5672:5672 # rabbit mq service
      - 15672:15672 # management page
  jds-mongo:
    image: mongo:4.2.3
    restart: always
    container_name: jds-mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  jds-mongo-express:
    image: mongo-express:0.54.0
    restart: always
    container_name: jds-mongo-express
    depends_on:
      - jds-mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: jds-mongo
  jds-redis:
    image: redis:6.0-rc1
    restart: always
    container_name: jds-redis
    ports:
      - 6379:6379
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: jds-dev-mongo
  jds-redis-phpredisadmin:
    image: erikdubbelboer/phpredisadmin:v1.13.1
    restart: always
    container_name: jds-dev-redis-phpredisadmin
    links:
      - jds-redis
    depends_on:
      - jds-redis
    ports:
      - 7780:80
    environment:
      REDIS_1_HOST: jds-redis
  jds-client-receiver:
    image: jds-client-receiver:0.0.1
    restart: always
    container_name: jds-client-receiver
    links:
      - jds-mongo   
      - jds-rabbit
    depends_on:
      - jds-mongo
      - jds-rabbit
    environment:
      jds_client_receiver_port: 8091
      jds_rabbitmq_host: jds-rabbit
      jds_rabbitmq_port: 5672
      jds_mongodb_host: jds-mongo
      jds_mongodb_port: 27017
    ports:
      - 8091:8091      
  jds-client-demo:
    image: jds-client-demo:0.0.1
    restart: always
    container_name: jds-client-demo
    links:
      - jds-client-receiver  
    depends_on:
      - jds-client-receiver
    environment:
      jds_client_receiver_host: jds-client-receiver
      jds_client_receiver_port: 8091
  jds-web-service:
    image: jds-web-service:0.0.1
    restart: always
    container_name: jds-web-service
    links:
      - jds-rabbit
      - jds-redis  
      - jds-mongo         
    depends_on:
      - jds-rabbit
      - jds-redis
      - jds-mongo
      - jds-client-receiver
    environment:
      jds_mongodb_host: jds-mongo
      jds_mongodb_port: 27017    
      jds_redis_host: jds-redis
      jds_redis_port: 6379    
    ports:
      - 28080:28080
  jds-web:
    image: jds-web:0.0.1
    restart: always
    container_name: jds-web
    links:
      - jds-rabbit   
      - jds-redis
      - jds-web-service
    depends_on:
      - jds-rabbit
      - jds-redis
      - jds-web-service
    environment:
      jds_web_service_host: jds-web-service
      jds_web_service_port: 28080    
      jds_redis_host: jds-redis
      jds_redis_port: 6379
      jds_rabbitmq_host: jds-rabbit
      jds_rabbitmq_port: 5672
    ports:
      - 18080:18080
