server:
  port: 18080

spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

  redis:
    host: ${jds_redis_host:127.0.0.1}
    port: ${jds_redis_port:6379}

  rabbitmq:
    host: ${jds_rabbitmq_host:127.0.0.1}
    port: ${jds_rabbitmq_port:5672}
    username: guest
    password: guest

outUrl:
  jds:
    baseUrl: ${jds_web_service_host:127.0.0.1}:${jds_web_service_port:28080}
    module:
      listSnapshot: http://${outUrl.jds.baseUrl}/listSnapshot
      listStatistics: http://${outUrl.jds.baseUrl}/listStatistics
      listMethodHierarchy: http://${outUrl.jds.baseUrl}/listMethodHierarchy     
      
logging:
  level:
    root: INFO
    org.springframework.web: trace
    org.springframework.data.mongodb.core: DEBUG
