spring:
  data:
    mongodb:
      host: 192.168.1.104
      port: 27017
      database: admin
      username: root
      password: example

  redis:
    host: 127.0.0.1

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    org.springframework.web: trace
    org.springframework.data.mongodb.core: DEBUG

NIOServer:
  profiles: dev
  port: 9999
  cacheSize: 1024    
