spring:
  data:
    mongodb:
      host: ${jds_mongodb_host:127.0.0.1}
      port: ${jds_mongodb_port:27017} 
      database: admin
      username: root
      password: example

  rabbitmq:
    host: ${jds_rabbitmq_host:127.0.0.1}
    port: ${jds_rabbitmq_port:5672} 
    username: guest
    password: guest

logging:
  level:
    root: INFO
    com.minirmb.jds: trace
    org.springframework.data.mongodb.core: INFO
  file:
    max-size: 50MB
    max-history: 20    
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}[lineno:%line]: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file:    "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}[lineno:%line]: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

NIOServer:
  port: 8091
  cacheSize: 1024    
