version: '3.1'

services:
  jpt-mongo:
    image: mongo:4.2.3
    restart: always
    ports:
      - 27017:27017
      - 28017:28017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

  jpt-mongoclient:
    image: mongoclient/mongoclient:4.0.1
    restart: always
    depends_on:
      - jpt-mongo
    ports:
      - 2000:3000
    environment:
      MONGO_URL: mongodb://jpt-mongo:27017

