server:
  port: 28080

spring:
  datasource:
    url: jdbc:h2:file:~/.h2/h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver

  data:
    mongodb:
      host: ${jds_mongodb_host:127.0.0.1}
      port: ${jds_mongodb_port:27017}
      database: admin
      username: root
      password: example

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  redis:
    host: ${jds_redis_host:127.0.0.1}
    port: ${jds_redis_port:6379}

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core: DEBUG
