server:
  port: 8899

spring:

  data:
    mongodb:
      host: ${jpt_mongodb_host:127.0.0.1}
      port: ${jpt_mongodb_port:27017}
      database: admin
      auto-index-creation: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

logging:
  level:
    root: INFO
    org.springframework.web: trace
    com.minirmb.jpt: INFO
    com.minirmb.jpt.receiver: DEBUG
#    org.springframework.data.mongodb.core: Trace

  file:
    max-size: 50MB
    max-history: 20
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}[lineno:%line]: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}[lineno:%line]: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'

NIOServer:
  port: 8877
  cacheSize: 1024
